/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => InlineAdmonitionPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian10 = require("obsidian");
var import_state2 = require("@codemirror/state");

// src/settings/inlineAdmonitionSettingTab.ts
var import_obsidian9 = require("obsidian");

// src/settings/editInlineAdmonitionModal.ts
var import_obsidian8 = require("obsidian");

// src/utils.ts
function encodeChar(char) {
  const charCode = char.charCodeAt(0);
  return `_x${charCode.toString(16).padStart(4, "0")}_`;
}
function sanitizeClassName(input) {
  input = input.trim();
  if (!/^[a-zA-Z_]/.test(input.charAt(0))) {
    input = "_" + input;
  }
  return input.split("").map((char) => {
    if (/^[a-zA-Z0-9\-_]$/.test(char)) {
      return char;
    } else {
      return encodeChar(char);
    }
  }).join("");
}
function appendOpacityToHexColor(hexColor, opacityPercent) {
  const hexCode = hexColor.trim().replace(/^#/g, "").substring(0, 6);
  return "#" + hexCode + convertAlphaToHex(opacityPercent);
}
function convertAlphaToHex(alphaDecimal) {
  if (alphaDecimal == null) {
    return "FF";
  }
  const alpha = alphaDecimal / 100;
  const alphaInt = Math.round(alpha * 255);
  const alphaHex = alphaInt.toString(16).toUpperCase();
  const paddedAlphaHex = alphaHex.padStart(2, "0");
  return paddedAlphaHex;
}
function borderCss(borderStyle, borderWidth, borderColor, borderRadius) {
  let css = "";
  if (borderStyle === "none") {
    css += " border: none;";
  } else if (borderStyle === "solid" || borderStyle === "dashed" || borderStyle === "dotted") {
    css += ` border: ${borderWidth}px ${borderStyle} ${borderColor};`;
  }
  css += ` border-radius: ${borderRadius}px;`;
  return css;
}
function textStyleCss(bold, italic, underline) {
  let css = "";
  if (bold) {
    css += " font-weight: bold;";
  }
  if (italic) {
    css += " font-style: italic;";
  }
  if (underline) {
    css += " text-decoration: underline;";
  }
  return css;
}

// node_modules/uuid/dist/esm-browser/rng.js
var getRandomValues;
var rnds8 = new Uint8Array(16);
function rng() {
  if (!getRandomValues) {
    getRandomValues = typeof crypto !== "undefined" && crypto.getRandomValues && crypto.getRandomValues.bind(crypto);
    if (!getRandomValues) {
      throw new Error("crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported");
    }
  }
  return getRandomValues(rnds8);
}

// node_modules/uuid/dist/esm-browser/stringify.js
var byteToHex = [];
for (let i2 = 0; i2 < 256; ++i2) {
  byteToHex.push((i2 + 256).toString(16).slice(1));
}
function unsafeStringify(arr, offset = 0) {
  return byteToHex[arr[offset + 0]] + byteToHex[arr[offset + 1]] + byteToHex[arr[offset + 2]] + byteToHex[arr[offset + 3]] + "-" + byteToHex[arr[offset + 4]] + byteToHex[arr[offset + 5]] + "-" + byteToHex[arr[offset + 6]] + byteToHex[arr[offset + 7]] + "-" + byteToHex[arr[offset + 8]] + byteToHex[arr[offset + 9]] + "-" + byteToHex[arr[offset + 10]] + byteToHex[arr[offset + 11]] + byteToHex[arr[offset + 12]] + byteToHex[arr[offset + 13]] + byteToHex[arr[offset + 14]] + byteToHex[arr[offset + 15]];
}

// node_modules/uuid/dist/esm-browser/native.js
var randomUUID = typeof crypto !== "undefined" && crypto.randomUUID && crypto.randomUUID.bind(crypto);
var native_default = {
  randomUUID
};

// node_modules/uuid/dist/esm-browser/v4.js
function v4(options, buf, offset) {
  if (native_default.randomUUID && !buf && !options) {
    return native_default.randomUUID();
  }
  options = options || {};
  const rnds = options.random || (options.rng || rng)();
  rnds[6] = rnds[6] & 15 | 64;
  rnds[8] = rnds[8] & 63 | 128;
  if (buf) {
    offset = offset || 0;
    for (let i2 = 0; i2 < 16; ++i2) {
      buf[offset + i2] = rnds[i2];
    }
    return buf;
  }
  return unsafeStringify(rnds);
}
var v4_default = v4;

// src/InlineAdmonitions/inlineAdmonition.ts
function defaultSharedFields() {
  return {
    slug: InlineAdmonition.generateSlug(),
    backgroundColor: "#f1f1f1",
    bgColorOpacityPercent: 100,
    color: "#000000",
    colorOpacityPercent: 100,
    prefixIcon: "",
    suffixIcon: "",
    fontFamily: "",
    hideBackground: false,
    borderColor: "#000000",
    borderWidth: 1,
    borderStyle: "",
    borderRadius: 4,
    bold: false,
    italic: false,
    underline: false
  };
}
function sharedFieldsFromData(data) {
  var _a, _b, _c, _d, _e, _f, _g, _h;
  return {
    slug: (_a = data.slug) != null ? _a : InlineAdmonition.generateSlug(),
    backgroundColor: data.backgroundColor,
    bgColorOpacityPercent: data.bgColorOpacityPercent,
    color: data.color,
    colorOpacityPercent: data.colorOpacityPercent,
    prefixIcon: data.prefixIcon,
    suffixIcon: data.suffixIcon,
    fontFamily: data.fontFamily || "",
    hideBackground: data.hideBackground || false,
    borderColor: (_b = data.borderColor) != null ? _b : "#000000",
    borderWidth: (_c = data.borderWidth) != null ? _c : 1,
    borderStyle: (_d = data.borderStyle) != null ? _d : "",
    borderRadius: (_e = data.borderRadius) != null ? _e : 4,
    bold: (_f = data.bold) != null ? _f : false,
    italic: (_g = data.italic) != null ? _g : false,
    underline: (_h = data.underline) != null ? _h : false
  };
}
var InlineAdmonition = class {
  constructor(fields) {
    this.toString = () => {
      return "InlineAdmonition(" + this.evalBackgroundColor() + ", " + this.type + ")";
    };
    this.slug = fields.slug;
    this.backgroundColor = fields.backgroundColor;
    this.bgColorOpacityPercent = fields.bgColorOpacityPercent;
    this.color = fields.color;
    this.colorOpacityPercent = fields.colorOpacityPercent;
    this.prefixIcon = fields.prefixIcon;
    this.suffixIcon = fields.suffixIcon;
    this.fontFamily = fields.fontFamily;
    this.hideBackground = fields.hideBackground;
    this.borderColor = fields.borderColor;
    this.borderWidth = fields.borderWidth;
    this.borderStyle = fields.borderStyle;
    this.borderRadius = fields.borderRadius;
    this.bold = fields.bold;
    this.italic = fields.italic;
    this.underline = fields.underline;
  }
  cssClasses() {
    return ["iad"];
  }
  simpleStyle() {
    let style = "";
    if (this.hideBackground) {
      style += "background-color: transparent; border: none; padding: 0; border-radius: 0;";
    } else {
      style += `background-color: ${this.evalBackgroundColor()};`;
      style += borderCss(this.borderStyle, this.borderWidth, this.borderColor, this.borderRadius);
    }
    style += ` color: ${this.evalColor()};`;
    if (this.fontFamily) {
      style += ` font-family: ${this.fontFamily};`;
    }
    style += textStyleCss(this.bold, this.italic, this.underline);
    return style;
  }
  copySettingsTo(other) {
    other.backgroundColor = this.backgroundColor;
    other.bgColorOpacityPercent = this.bgColorOpacityPercent;
    other.color = this.color;
    other.colorOpacityPercent = this.colorOpacityPercent;
    other.prefixIcon = this.prefixIcon;
    other.suffixIcon = this.suffixIcon;
    other.fontFamily = this.fontFamily;
    other.hideBackground = this.hideBackground;
    other.borderColor = this.borderColor;
    other.borderWidth = this.borderWidth;
    other.borderStyle = this.borderStyle;
    other.borderRadius = this.borderRadius;
    other.bold = this.bold;
    other.italic = this.italic;
    other.underline = this.underline;
  }
  evalBackgroundColor() {
    return appendOpacityToHexColor(this.backgroundColor, this.bgColorOpacityPercent);
  }
  evalColor() {
    return appendOpacityToHexColor(this.color, this.colorOpacityPercent);
  }
  static generateSlug() {
    return v4_default();
  }
};

// src/InlineAdmonitions/prefixInlineAdmonition.ts
var import_obsidian5 = require("obsidian");

// src/InlineAdmonitions/suffixInlineAdmonition.ts
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var SuffixInlineAdmonition = class extends InlineAdmonition {
  constructor(suffix, hideTriggerString, fields) {
    super(fields);
    this.type = "suffix" /* Suffix */;
    this.toString = () => {
      return "SuffixInlineAdmonition(" + this.suffix + ", hidePrefix: " + this.hideTriggerString + ")";
    };
    this.suffix = suffix;
    this.hideTriggerString = hideTriggerString;
  }
  static create() {
    return new SuffixInlineAdmonition("", false, defaultSharedFields());
  }
  static unmarshal(data) {
    var _a, _b;
    if (data.type != "suffix" /* Suffix */) {
      throw new Error("Cannot unmarshal data into SuffixInlineAdmonition: Wrong type: " + data.type);
    }
    return new SuffixInlineAdmonition((_a = data.suffix) != null ? _a : "", (_b = data.hideTriggerString) != null ? _b : false, sharedFieldsFromData(data));
  }
  process(codeElement) {
    if (codeElement.getText().endsWith(this.suffix)) {
      this.cssClasses().forEach((c2) => codeElement.classList.add(c2));
      if (this.hideTriggerString) {
        codeElement.setText(codeElement.getText().replace(new RegExp(this.suffix + "$"), ""));
      }
      if (this.prefixIcon) {
        const iconElement = createSpan({ cls: "admonition-icon-left" });
        (0, import_obsidian.setIcon)(iconElement, this.prefixIcon);
        codeElement.prepend(iconElement);
      }
      if (this.suffixIcon) {
        const iconElement = createSpan({ cls: "admonition-icon-right" });
        (0, import_obsidian.setIcon)(iconElement, this.suffixIcon);
        codeElement.append(iconElement);
      }
    }
  }
  applyTo(node, content, builder) {
    if (content.endsWith(this.suffix)) {
      builder.add(
        node.from,
        node.to,
        import_view.Decoration.mark({
          inclusive: true,
          attributes: { class: this.cssClasses().join(" ") },
          tagName: "span"
        })
      );
      if (this.hideTriggerString) {
        builder.add(
          node.to - this.suffix.length,
          node.to,
          import_view.Decoration.mark({
            inclusive: true,
            attributes: { class: "iad-hidden" },
            tagName: "span"
          })
        );
      }
    }
  }
  cssClasses() {
    const classes = super.cssClasses();
    classes.push("iad-suffix");
    classes.push("iad-suffix-" + sanitizeClassName(this.suffix));
    return classes;
  }
  sampleText() {
    return "sample text " + this.suffix;
  }
  buildSettings(contentEl, updateSampleFunction) {
    const results = new Array();
    results.push(new import_obsidian.Setting(contentEl).setName("Suffix").setDesc("Text the code span must end with to match.").addText(
      (text) => text.setPlaceholder("Enter suffix").setValue(this.suffix).onChange((value) => {
        this.suffix = value;
        updateSampleFunction();
      })
    ));
    results.push(
      new import_obsidian.Setting(contentEl).setName("Hide suffix text").setDesc("Remove the suffix from the displayed admonition.").addToggle(
        (toggle) => toggle.setValue(this.hideTriggerString).onChange((val) => {
          this.hideTriggerString = val;
          updateSampleFunction();
        })
      )
    );
    return results;
  }
  asTitle() {
    return "Suffix type (trigger: " + this.suffix + ")";
  }
};

// src/InlineAdmonitions/containsInlineAdmonition.ts
var import_obsidian2 = require("obsidian");
var import_view2 = require("@codemirror/view");
var ContainsInlineAdmonition = class extends InlineAdmonition {
  constructor(contains, fields) {
    super(fields);
    this.type = "contains" /* Contains */;
    this.toString = () => {
      return "ContainsInlineAdmonition(" + this.contains + ")";
    };
    this.contains = contains;
  }
  static create() {
    return new ContainsInlineAdmonition("", defaultSharedFields());
  }
  static unmarshal(data) {
    var _a;
    if (data.type != "contains" /* Contains */) {
      throw new Error("Cannot unmarshal data into ContainsInlineAdmonition: Wrong type: " + data.type);
    }
    return new ContainsInlineAdmonition((_a = data.contains) != null ? _a : "", sharedFieldsFromData(data));
  }
  process(codeElement) {
    if (codeElement.getText().contains(this.contains)) {
      this.cssClasses().forEach((c2) => codeElement.classList.add(c2));
      if (this.prefixIcon) {
        const iconElement = createSpan({ cls: "admonition-icon-left" });
        (0, import_obsidian2.setIcon)(iconElement, this.prefixIcon);
        codeElement.prepend(iconElement);
      }
      if (this.suffixIcon) {
        const iconElement = createSpan({ cls: "admonition-icon-right" });
        (0, import_obsidian2.setIcon)(iconElement, this.suffixIcon);
        codeElement.append(iconElement);
      }
    }
  }
  applyTo(node, content, builder) {
    if (content.contains(this.contains)) {
      builder.add(
        node.from,
        node.to,
        import_view2.Decoration.mark({
          inclusive: true,
          attributes: { class: this.cssClasses().join(" ") },
          tagName: "span"
        })
      );
    }
  }
  cssClasses() {
    const classes = super.cssClasses();
    classes.push("iad-contains");
    classes.push("iad-contains-" + sanitizeClassName(this.contains));
    return classes;
  }
  sampleText() {
    return "sample " + this.contains + " text";
  }
  buildSettings(contentEl, updateSampleFunction) {
    const results = new Array();
    results.push(new import_obsidian2.Setting(contentEl).setName("Contains").setDesc("Text the code span must contain to match.").addText(
      (text) => text.setPlaceholder("Enter contains").setValue(this.contains).onChange((value) => {
        this.contains = value;
        updateSampleFunction();
      })
    ));
    return results;
  }
  asTitle() {
    return "Contains type (trigger: " + this.contains + ")";
  }
};

// src/InlineAdmonitions/inlineAdmonitionType.ts
var import_obsidian4 = require("obsidian");

// src/InlineAdmonitions/regexInlineAdmonition.ts
var import_obsidian3 = require("obsidian");
var import_view3 = require("@codemirror/view");
var RegexInlineAdmonition = class extends InlineAdmonition {
  constructor(regex, sampleInput, fields) {
    super(fields);
    this.type = "regex" /* Regex */;
    this.toString = () => {
      return "RegexInlineAdmonition(/" + this.regex + "/)";
    };
    this.regex = regex;
    this.sampleInput = sampleInput;
  }
  static create() {
    return new RegexInlineAdmonition("", "", defaultSharedFields());
  }
  static unmarshal(data) {
    var _a, _b;
    if (data.type != "regex" /* Regex */) {
      throw new Error("Cannot unmarshal data into RegexInlineAdmonition: Wrong type: " + data.type);
    }
    return new RegexInlineAdmonition((_a = data.regex) != null ? _a : "", (_b = data.sampleInput) != null ? _b : "", sharedFieldsFromData(data));
  }
  process(codeElement) {
    try {
      const regex = new RegExp(this.regex);
      if (regex.test(codeElement.getText())) {
        this.cssClasses().forEach((c2) => codeElement.classList.add(c2));
        if (this.prefixIcon) {
          const iconElement = createSpan({ cls: "admonition-icon-left" });
          (0, import_obsidian3.setIcon)(iconElement, this.prefixIcon);
          codeElement.prepend(iconElement);
        }
        if (this.suffixIcon) {
          const iconElement = createSpan({ cls: "admonition-icon-right" });
          (0, import_obsidian3.setIcon)(iconElement, this.suffixIcon);
          codeElement.append(iconElement);
        }
      }
    } catch (e2) {
      console.error("Error processing regex admonition: ", e2);
    }
  }
  applyTo(node, content, builder) {
    try {
      const regex = new RegExp(this.regex);
      if (regex.test(content)) {
        builder.add(
          node.from,
          node.to,
          import_view3.Decoration.mark({
            inclusive: true,
            attributes: { class: this.cssClasses().join(" ") },
            tagName: "span"
          })
        );
      }
    } catch (e2) {
      console.error("Error applying regex admonition: ", e2);
    }
  }
  cssClasses() {
    const classes = super.cssClasses();
    classes.push("iad-regex");
    classes.push("iad-regex-" + sanitizeClassName(this.regex));
    return classes;
  }
  sampleText() {
    return "sample " + this.sampleInput + " match";
  }
  buildSettings(contentEl, updateSampleFunction) {
    let iconButton;
    const results = new Array();
    results.push(new import_obsidian3.Setting(contentEl).setName("Regex").setDesc("Code span matches this regular expression to trigger this formatting.").addText(
      (text) => text.setPlaceholder("Enter regex").setValue(this.regex).onChange((value) => {
        this.regex = value;
        updateSampleFunction();
      })
    ));
    results.push(new import_obsidian3.Setting(contentEl).setName("Sample input").setDesc("Test text for your regex; also drives the sample preview.").addText((text) => text.setPlaceholder("Text match for regex").setValue(this.sampleInput).onChange((value) => {
      this.sampleInput = value;
      const regex = new RegExp(this.regex);
      const ok = regex.test(value);
      iconButton.setIcon(ok ? "checkmark" : "alert-triangle");
      updateSampleFunction();
    })).addButton((btn) => {
      iconButton = btn.setIcon(new RegExp(this.regex).test(this.sampleInput) ? "checkmark" : "alert-triangle").setTooltip("Regex match");
    }));
    return results;
  }
  asTitle() {
    return "Regex type (trigger: /" + this.regex + "/)";
  }
};

// src/InlineAdmonitions/inlineAdmonitionType.ts
var InlineAdmonitionType = /* @__PURE__ */ ((InlineAdmonitionType2) => {
  InlineAdmonitionType2["Prefix"] = "prefix";
  InlineAdmonitionType2["Suffix"] = "suffix";
  InlineAdmonitionType2["Contains"] = "contains";
  InlineAdmonitionType2["Regex"] = "regex";
  return InlineAdmonitionType2;
})(InlineAdmonitionType || {});
((InlineAdmonitionType2) => {
  function create(type) {
    switch (type) {
      case "prefix" /* Prefix */:
        return PrefixInlineAdmonition.create();
      case "suffix" /* Suffix */:
        return SuffixInlineAdmonition.create();
      case "contains" /* Contains */:
        return ContainsInlineAdmonition.create();
      case "regex" /* Regex */:
        return RegexInlineAdmonition.create();
      default:
        throw new Error("Cannot create, invalid Inline Admonition type");
    }
  }
  InlineAdmonitionType2.create = create;
  function from(type) {
    switch (type) {
      case "prefix" /* Prefix */:
        return "prefix" /* Prefix */;
      case "suffix" /* Suffix */:
        return "suffix" /* Suffix */;
      case "contains" /* Contains */:
        return "contains" /* Contains */;
      case "regex" /* Regex */:
        return "regex" /* Regex */;
      default:
        throw new Error("Invalid Inline Admonition type: " + type);
    }
  }
  InlineAdmonitionType2.from = from;
  function createFrom(type) {
    return create(from(type));
  }
  InlineAdmonitionType2.createFrom = createFrom;
  function unmarshal(data) {
    const type = from(data.type);
    switch (type) {
      case "prefix" /* Prefix */:
        return PrefixInlineAdmonition.unmarshal(data);
      case "suffix" /* Suffix */:
        return SuffixInlineAdmonition.unmarshal(data);
      case "contains" /* Contains */:
        return ContainsInlineAdmonition.unmarshal(data);
      case "regex" /* Regex */:
        return RegexInlineAdmonition.unmarshal(data);
      default:
        throw new Error("Cannot Unmarshal, invalid Inline Admonition type: " + String(type));
    }
  }
  InlineAdmonitionType2.unmarshal = unmarshal;
  function tooltip() {
    return `
The "type" defines what triggers an Inline Admonition
		
 - Prefix: Triggered if a codeblock starts with the string.
 - Suffix: Triggered if a codeblock ends with the string.
 - Contains: Triggered if a codeblock contains the string anywhere within it.
 - Regex: Triggered if a codeblock matches the regular expression.
 `;
  }
  InlineAdmonitionType2.tooltip = tooltip;
})(InlineAdmonitionType || (InlineAdmonitionType = {}));
var TypeTooltipModal = class extends import_obsidian4.Modal {
  onOpen() {
    const { contentEl } = this;
    contentEl.createDiv({
      text: InlineAdmonitionType.tooltip(),
      cls: "iad-pre-wrap"
    });
  }
};

// src/InlineAdmonitions/prefixInlineAdmonition.ts
var import_view4 = require("@codemirror/view");
var PrefixInlineAdmonition = class extends InlineAdmonition {
  constructor(prefix, hideTriggerString, fields) {
    super(fields);
    this.type = "prefix" /* Prefix */;
    this.toString = () => {
      return "PrefixInlineAdmonition(" + this.prefix + ", hidePrefix: " + this.hideTriggerString + ")";
    };
    this.prefix = prefix;
    this.hideTriggerString = hideTriggerString;
  }
  static create() {
    return new PrefixInlineAdmonition("", false, defaultSharedFields());
  }
  static unmarshal(data) {
    var _a, _b;
    if (data.type != "prefix" /* Prefix */) {
      throw new Error("Cannot unmarshal data into PrefixInlineAdmonition: Wrong type: " + data.type);
    }
    return new PrefixInlineAdmonition((_a = data.prefix) != null ? _a : "", (_b = data.hideTriggerString) != null ? _b : false, sharedFieldsFromData(data));
  }
  process(codeElement) {
    if (codeElement.getText().startsWith(this.prefix)) {
      this.cssClasses().forEach((c2) => codeElement.classList.add(c2));
      if (this.hideTriggerString) {
        codeElement.setText(codeElement.getText().replace(this.prefix, ""));
      }
      if (this.prefixIcon) {
        const iconElement = createSpan({ cls: "admonition-icon-left" });
        (0, import_obsidian5.setIcon)(iconElement, this.prefixIcon);
        codeElement.prepend(iconElement);
      }
      if (this.suffixIcon) {
        const iconElement = createSpan({ cls: "admonition-icon-right" });
        (0, import_obsidian5.setIcon)(iconElement, this.suffixIcon);
        codeElement.append(iconElement);
      }
    }
  }
  applyTo(node, content, builder) {
    if (content.startsWith(this.prefix)) {
      builder.add(
        node.from,
        node.to,
        import_view4.Decoration.mark({
          inclusive: true,
          attributes: { class: this.cssClasses().join(" ") },
          tagName: "span"
        })
      );
      if (this.hideTriggerString) {
        builder.add(
          node.from,
          node.from + this.prefix.length,
          import_view4.Decoration.mark({
            inclusive: true,
            attributes: { class: "iad-hidden" },
            tagName: "span"
          })
        );
      }
    }
  }
  cssClasses() {
    const classes = super.cssClasses();
    classes.push("iad-prefix");
    classes.push("iad-prefix-" + sanitizeClassName(this.prefix));
    return classes;
  }
  sampleText() {
    return this.prefix + " sample text";
  }
  buildSettings(contentEl, updateSampleFunction) {
    const results = new Array();
    results.push(new import_obsidian5.Setting(contentEl).setName("Prefix").setDesc("Text the code span must start with to match.").addText(
      (text) => text.setPlaceholder("Enter prefix").setValue(this.prefix).onChange((value) => {
        this.prefix = value;
        updateSampleFunction();
      })
    ));
    results.push(
      new import_obsidian5.Setting(contentEl).setName("Hide prefix text").setDesc("Remove the prefix from the displayed admonition.").addToggle(
        (toggle) => toggle.setValue(this.hideTriggerString).onChange((val) => {
          this.hideTriggerString = val;
          updateSampleFunction();
        })
      )
    );
    return results;
  }
  asTitle() {
    return "Prefix type (trigger: " + this.prefix + ")";
  }
};

// src/settings/IconSelectionModal.ts
var import_obsidian6 = require("obsidian");
var NO_ICON = "";
var IconSelectionModal = class extends import_obsidian6.FuzzySuggestModal {
  constructor(app, currentIcon, onSelect) {
    super(app);
    this.onSelect = onSelect;
    this.setPlaceholder("Search icons\u2026");
  }
  getItems() {
    const icons = (0, import_obsidian6.getIconIds)().filter((id) => id.startsWith("lucide-")).map((id) => id.slice("lucide-".length));
    return [NO_ICON, ...icons];
  }
  getItemText(item) {
    return item === NO_ICON ? "No icon" : item;
  }
  renderSuggestion(match, el) {
    const id = match.item;
    if (id !== NO_ICON) {
      (0, import_obsidian6.setIcon)(el.createSpan({ cls: "iad-suggest-icon" }), id);
    }
    el.createSpan({ text: this.getItemText(id) });
  }
  onChooseItem(item) {
    this.onSelect(item);
  }
};

// src/settings/FontSelectionModal.ts
var import_obsidian7 = require("obsidian");
var GENERIC_FAMILIES = [
  "serif",
  "sans-serif",
  "monospace",
  "cursive",
  "fantasy",
  "system-ui",
  "ui-serif",
  "ui-sans-serif",
  "ui-monospace",
  "ui-rounded"
];
var DEFAULT_FONT = "";
var FontSelectionModal = class extends import_obsidian7.FuzzySuggestModal {
  constructor(app, items, onSelect) {
    super(app);
    this.items = items;
    this.onSelect = onSelect;
    this.setPlaceholder("Search fonts\u2026");
  }
  // System fonts are queried asynchronously, so build the item list first, then open.
  static async open(app, currentFont, onSelect) {
    const systemFonts = await FontSelectionModal.getSystemFonts();
    const items = [DEFAULT_FONT, ...GENERIC_FAMILIES, ...systemFonts];
    new FontSelectionModal(app, items, onSelect).open();
  }
  getItems() {
    return this.items;
  }
  getItemText(item) {
    return item === DEFAULT_FONT ? "Default (theme font)" : item;
  }
  renderSuggestion(match, el) {
    const font = match.item;
    const label = el.createSpan({ text: this.getItemText(font) });
    if (font !== DEFAULT_FONT) {
      label.style.setProperty("font-family", font);
    }
  }
  onChooseItem(item) {
    this.onSelect(item);
  }
  static async getSystemFonts() {
    try {
      const queryLocalFonts = window.queryLocalFonts;
      if (!queryLocalFonts) {
        return [];
      }
      const fonts = await queryLocalFonts();
      const families = /* @__PURE__ */ new Set();
      for (const font of fonts) {
        families.add(font.family);
      }
      return [...families].sort((a2, b) => a2.localeCompare(b));
    } catch (e2) {
      return [];
    }
  }
};

// src/settings/editInlineAdmonitionModal.ts
var EditInlineAdmonitionModal = class extends import_obsidian8.Modal {
  constructor(app, toEdit, onSubmit) {
    super(app);
    this.typeSettings = new Array();
    this.result = toEdit ? toEdit : PrefixInlineAdmonition.create();
    this.onSubmit = onSubmit;
  }
  static edit(app, toEdit, onSubmit) {
    return new EditInlineAdmonitionModal(app, toEdit, onSubmit);
  }
  static new(app, onSubmit) {
    return new EditInlineAdmonitionModal(app, PrefixInlineAdmonition.create(), onSubmit);
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("iad-edit-modal");
    const header2 = contentEl.createDiv({ cls: "iad-modal-header" });
    const submitSetting = new import_obsidian8.Setting(header2).addButton((btn) => btn.setButtonText("Submit").setCta().onClick(() => {
      this.close();
      this.onSubmit(this.result);
    }));
    this.sample = submitSetting.nameEl.createEl("code", { cls: "iad-sample" });
    this.updateSample();
    this.body = contentEl.createDiv({ cls: "iad-modal-body" });
    const trigger = this.section("Trigger", true);
    new import_obsidian8.Setting(trigger).setName("Trigger type").setDesc("What text turns an inline code span into this admonition.").setTooltip(InlineAdmonitionType.tooltip()).addDropdown((dc) => dc.addOption("prefix" /* Prefix */, "prefix" /* Prefix */).addOption("suffix" /* Suffix */, "suffix" /* Suffix */).addOption("contains" /* Contains */, "contains" /* Contains */).addOption("regex" /* Regex */, "regex" /* Regex */).setValue(this.result.type).onChange((value) => {
      this.clearTypeSettings();
      const old = this.result;
      this.result = InlineAdmonitionType.createFrom(value);
      old.copySettingsTo(this.result);
      this.appendTypeSettings();
    })).addButton(
      (btn) => btn.setIcon("help-circle").onClick(() => {
        new TypeTooltipModal(this.app).open();
      })
    );
    this.triggerBody = trigger;
    this.appendTypeSettings();
    const background = this.section("Background");
    new import_obsidian8.Setting(background).setName("Background color").setDesc("Fill color behind the text.").addColorPicker(
      (cp) => cp.setValue(this.result.backgroundColor).onChange((val) => {
        this.result.backgroundColor = val;
        this.updateSample();
      })
    );
    new import_obsidian8.Setting(background).setName("Background opacity").setDesc("How opaque the fill is. 0% is fully transparent.").addSlider((s2) => s2.setLimits(0, 100, 1).setValue(this.result.bgColorOpacityPercent).setDynamicTooltip().onChange((val) => {
      this.result.bgColorOpacityPercent = val;
      this.updateSample();
    }));
    new import_obsidian8.Setting(background).setName("Blend into text").setDesc("Drop the fill, padding, and rounded corners so it flows inline with surrounding text.").addToggle(
      (toggle) => toggle.setValue(this.result.hideBackground).onChange((val) => {
        this.result.hideBackground = val;
        this.updateSample();
      })
    );
    const text = this.section("Text & font");
    new import_obsidian8.Setting(text).setName("Text color").setDesc("Color of the admonition text.").addColorPicker(
      (cp) => cp.setValue(this.result.color).onChange((val) => {
        this.result.color = val;
        this.updateSample();
      })
    );
    new import_obsidian8.Setting(text).setName("Text opacity").setDesc("How opaque the text is. 0% is fully transparent.").addSlider((s2) => s2.setLimits(0, 100, 1).setValue(this.result.colorOpacityPercent).setDynamicTooltip().onChange((val) => {
      this.result.colorOpacityPercent = val;
      this.updateSample();
    }));
    new import_obsidian8.Setting(text).setName("Font").setDesc("Font for the admonition text.").addButton((btn) => {
      btn.setButtonText(this.result.fontFamily || "Font\u2026");
      return btn.onClick(async () => {
        await FontSelectionModal.open(this.app, this.result.fontFamily, (selectedFont) => {
          this.result.fontFamily = selectedFont;
          btn.setButtonText(selectedFont || "Font\u2026");
          this.updateSample();
        });
      });
    });
    new import_obsidian8.Setting(text).setName("Bold").setDesc("Bold the text.").addToggle((toggle) => toggle.setValue(this.result.bold).onChange((val) => {
      this.result.bold = val;
      this.updateSample();
    }));
    new import_obsidian8.Setting(text).setName("Italic").setDesc("Italicize the text.").addToggle((toggle) => toggle.setValue(this.result.italic).onChange((val) => {
      this.result.italic = val;
      this.updateSample();
    }));
    new import_obsidian8.Setting(text).setName("Underline").setDesc("Underline the text.").addToggle((toggle) => toggle.setValue(this.result.underline).onChange((val) => {
      this.result.underline = val;
      this.updateSample();
    }));
    const border = this.section("Border");
    new import_obsidian8.Setting(border).setName("Border style").setDesc("Line style for the border.").addDropdown((dc) => dc.addOption("", "Default (theme)").addOption("none", "None").addOption("solid", "Solid").addOption("dashed", "Dashed").addOption("dotted", "Dotted").setValue(this.result.borderStyle).onChange((val) => {
      this.result.borderStyle = val;
      this.updateSample();
    }));
    new import_obsidian8.Setting(border).setName("Border width").setDesc("Border thickness in pixels (when a style is set).").addSlider((s2) => s2.setLimits(0, 10, 1).setValue(this.result.borderWidth).setDynamicTooltip().onChange((val) => {
      this.result.borderWidth = val;
      this.updateSample();
    }));
    new import_obsidian8.Setting(border).setName("Border color").setDesc("Color of the border.").addColorPicker((cp) => cp.setValue(this.result.borderColor).onChange((val) => {
      this.result.borderColor = val;
      this.updateSample();
    }));
    new import_obsidian8.Setting(border).setName("Corner radius").setDesc("Roundness of the corners, in pixels.").addSlider((s2) => s2.setLimits(0, 20, 1).setValue(this.result.borderRadius).setDynamicTooltip().onChange((val) => {
      this.result.borderRadius = val;
      this.updateSample();
    }));
    const icons = this.section("Icons");
    this.addIconSetting(
      icons,
      "Leading icon",
      "Icon shown before the text.",
      () => this.result.prefixIcon,
      (val) => this.result.prefixIcon = val
    );
    this.addIconSetting(
      icons,
      "Trailing icon",
      "Icon shown after the text.",
      () => this.result.suffixIcon,
      (val) => this.result.suffixIcon = val
    );
  }
  // Builds a collapsible <details> section and returns its body element for rows.
  section(title, open = false) {
    const details = this.body.createEl("details", { cls: "iad-section" });
    if (open)
      details.setAttr("open", "");
    const summary = details.createEl("summary", { cls: "iad-section-title" });
    summary.createSpan({ cls: "iad-section-label", text: title });
    return details.createDiv({ cls: "iad-section-body" });
  }
  // A row whose button opens the icon picker; get/set read and write the chosen icon.
  addIconSetting(parent, name, desc, get, set) {
    new import_obsidian8.Setting(parent).setName(name).setDesc(desc).addButton((btn) => {
      const render = () => {
        if (get()) {
          btn.setIcon(get());
        } else {
          btn.setButtonText("Icon\u2026");
        }
      };
      render();
      return btn.onClick(() => {
        new IconSelectionModal(this.app, get(), (selectedIcon) => {
          set(selectedIcon);
          render();
          this.updateSample();
        }).open();
      });
    });
  }
  updateSample() {
    this.sample.className = "iad-sample";
    this.sample.setText(this.result.sampleText());
    this.result.process(this.sample);
    this.sample.setAttr("style", this.result.simpleStyle());
  }
  clearTypeSettings() {
    this.typeSettings.forEach((value) => value.settingEl.remove());
  }
  appendTypeSettings() {
    this.typeSettings = this.result.buildSettings(this.triggerBody, () => this.updateSample());
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/settings/inlineAdmonitionSettingTab.ts
var InlineAdmonitionSettingTab = class extends import_obsidian9.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian9.Setting(containerEl).addButton((b) => b.setButtonText("Create new inline admonition").onClick(async (evt) => {
      EditInlineAdmonitionModal.new(this.app, async (result) => {
        this.plugin.settings.inlineAdmonitions.set(result.slug, result);
        await this.plugin.saveSettings();
        this.rebuildSettingRows(containerEl);
      }).open();
    }));
    this.rebuildSettingRows(containerEl);
  }
  // Renders the "samples" with options in the main settings view
  rebuildSettingRows(containerEl) {
    containerEl.findAll(".iad-setting-row").forEach((e2) => e2.remove());
    new Map([...this.plugin.settings.inlineAdmonitions].sort()).forEach((iad, identifier) => {
      this.displaySampleIAD(containerEl, iad, identifier);
    });
  }
  // Renders a single Inline Admonition "sample" with options
  displaySampleIAD(containerEl, iad, identifier) {
    const row = containerEl.createDiv();
    row.addClass("iad-setting-row");
    row.createSpan({
      text: iad.asTitle(),
      cls: "iad-setting-row-title"
    });
    const sample = row.createEl("code", { text: iad.sampleText(), cls: "iad-sample" });
    iad.process(sample);
    const editButton = row.createEl("button", { text: "Edit" });
    editButton.addEventListener("click", (evt) => {
      EditInlineAdmonitionModal.edit(this.app, iad, async (result) => {
        this.plugin.settings.inlineAdmonitions.delete(identifier);
        this.plugin.settings.inlineAdmonitions.set(result.slug, result);
        await this.plugin.saveSettings();
        this.rebuildSettingRows(containerEl);
      }).open();
    });
    const deleteButton = row.createEl("button", { text: "Delete" });
    deleteButton.addEventListener("click", async (evt) => {
      this.plugin.settings.inlineAdmonitions.delete(identifier);
      await this.plugin.saveSettings();
      row.remove();
    });
  }
};

// src/settings/inlineAdmonitionSettings.ts
var InlineAdmonitionSettingsIO;
((InlineAdmonitionSettingsIO2) => {
  function marshal(settings) {
    const inlineAdmonitions = {};
    for (const [slug, iad] of settings.inlineAdmonitions.entries()) {
      inlineAdmonitions[slug] = iad;
    }
    return { version: settings.version, inlineAdmonitions };
  }
  InlineAdmonitionSettingsIO2.marshal = marshal;
  function unmarshalAndMigrate(data) {
    const persisted = Object.assign(
      {},
      defaultPersistedSettings(),
      data != null ? data : {}
    );
    const [migrated, dataMigrated] = migrateData(persisted);
    const iads = /* @__PURE__ */ new Map();
    for (const identifier in migrated.inlineAdmonitions) {
      const typedIAD = InlineAdmonitionType.unmarshal(migrated.inlineAdmonitions[identifier]);
      iads.set(typedIAD.slug, typedIAD);
    }
    return [{ version: migrated.version, inlineAdmonitions: iads }, dataMigrated];
  }
  InlineAdmonitionSettingsIO2.unmarshalAndMigrate = unmarshalAndMigrate;
  function migrateData(settings) {
    let dataMigrated = false;
    if (settings.version == void 0 || settings.version === 0) {
      const iads = {};
      for (const identifier in settings.inlineAdmonitions) {
        const iad = settings.inlineAdmonitions[identifier];
        if (iad.type === void 0) {
          iad.type = "prefix" /* Prefix */;
        }
        if (iad.slug === void 0) {
          iad.slug = InlineAdmonition.generateSlug();
        }
        iads[iad.slug] = iad;
      }
      settings.inlineAdmonitions = iads;
      settings.version = 1;
      dataMigrated = true;
    }
    if (settings.version === 1) {
      for (const identifier in settings.inlineAdmonitions) {
        const iad = settings.inlineAdmonitions[identifier];
        if ((iad.type === "prefix" /* Prefix */ || iad.type === "suffix" /* Suffix */) && iad.hideTriggerString === void 0) {
          iad.hideTriggerString = false;
        }
      }
      settings.version = 2;
      dataMigrated = true;
    }
    if (settings.version === 2) {
      for (const identifier in settings.inlineAdmonitions) {
        const iad = settings.inlineAdmonitions[identifier];
        if (iad.fontFamily === void 0) {
          iad.fontFamily = "";
        }
      }
      settings.version = 3;
      dataMigrated = true;
    }
    if (settings.version === 3) {
      for (const identifier in settings.inlineAdmonitions) {
        const iad = settings.inlineAdmonitions[identifier];
        if (iad.hideBackground === void 0) {
          iad.hideBackground = false;
        }
      }
      settings.version = 4;
      dataMigrated = true;
    }
    if (settings.version === 4) {
      for (const identifier in settings.inlineAdmonitions) {
        const iad = settings.inlineAdmonitions[identifier];
        if (iad.borderColor === void 0) {
          iad.borderColor = "#000000";
        }
        if (iad.borderWidth === void 0) {
          iad.borderWidth = 1;
        }
        if (iad.borderStyle === void 0) {
          iad.borderStyle = "";
        }
        if (iad.borderRadius === void 0) {
          iad.borderRadius = 4;
        }
        if (iad.bold === void 0) {
          iad.bold = false;
        }
        if (iad.italic === void 0) {
          iad.italic = false;
        }
        if (iad.underline === void 0) {
          iad.underline = false;
        }
      }
      settings.version = 5;
      dataMigrated = true;
    }
    return [settings, dataMigrated];
  }
  function defaultPersistedSettings() {
    return { version: 0, inlineAdmonitions: {} };
  }
})(InlineAdmonitionSettingsIO || (InlineAdmonitionSettingsIO = {}));

// src/InlineAdmonitions/inlineAdmonitionsPostProcessor.ts
var InlineAdmonitionsPostProcessor = class {
  constructor(settings) {
    this.settings = settings;
  }
  postProcess(element, context) {
    element.findAll("code").forEach((codeblock) => {
      this.settings.inlineAdmonitions.forEach((iad) => iad.process(codeblock));
    });
  }
};

// src/InlineAdmonitions/InlineAdmonitionExtension.ts
var import_view5 = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_language = require("@codemirror/language");
function inlineAdmonitionPlugin(admonitions) {
  return import_view5.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = this.buildDecorations(view);
      }
      update(update) {
        if (update.docChanged || update.viewportChanged) {
          this.decorations = this.buildDecorations(update.view);
        }
      }
      buildDecorations(view) {
        const builder = new import_state.RangeSetBuilder();
        for (const { from, to } of view.visibleRanges) {
          (0, import_language.syntaxTree)(view.state).iterate({
            from,
            to,
            enter: (node) => {
              if (node.type.name.contains("inline-code")) {
                const content = view.state.doc.sliceString(node.from, node.to);
                admonitions.forEach((iad) => iad.applyTo(node, content, builder));
                return false;
              }
            }
          });
        }
        return builder.finish();
      }
    },
    {
      decorations: (view) => view.decorations
    }
  );
}

// src/io/snippets.ts
function snippetDir(app) {
  return `${app.vault.configDir}/snippets`;
}
function snippetPath(app, filename) {
  return `${app.vault.configDir}/snippets/${filename}`;
}
async function readSnippetFile(app, filename) {
  return await app.vault.adapter.read(`${snippetPath(app, filename)}`);
}
async function createSnippetFile(app, filename, data = "") {
  await _validatefilename(app, filename);
  await _createSnippetDirectoryIfNotExists(app);
  await app.vault.adapter.write(`${snippetPath(app, filename)}`, data);
}
async function writeSnippetFile(app, filename, data) {
  await app.vault.adapter.write(`${snippetPath(app, filename)}`, data);
}
async function snippetExists(app, filename) {
  return app.vault.adapter.exists(`${snippetPath(app, filename)}`);
}
async function _createSnippetDirectoryIfNotExists(app) {
  if (!await app.vault.adapter.exists(snippetDir(app))) {
    await app.vault.adapter.mkdir(snippetDir(app));
  }
}
async function _validatefilename(app, value) {
  const errors = { exists: "", regex: "" };
  if (value.length > 0 && await snippetExists(app, value)) {
    errors.exists = "File already exists.";
  }
  const regex = /^[0-9a-zA-Z\-_ ]+\.css$/;
  if (!regex.test(value)) {
    errors.regex = "Must end with .css and only contain alphanumeric, spaces, dashes, or underscore characters.";
  }
  if (Object.values(errors).some((x) => x !== "")) {
    const message = Object.values(errors).filter((x) => x !== "").reduce((acc, curr) => `${acc}
${curr}`, "Failed to create file.");
    throw new Error(message);
  }
}

// node_modules/@adobe/css-tools/dist/esm/adobe-css-tools.mjs
var t = class extends Error {
  constructor(t2, i2, e2, s2, n2) {
    super(`${t2}:${e2}:${s2}: ${i2}`);
    __publicField(this, "reason");
    __publicField(this, "filename");
    __publicField(this, "line");
    __publicField(this, "column");
    __publicField(this, "source");
    this.reason = i2, this.filename = t2, this.line = e2, this.column = s2, this.source = n2;
  }
};
var i = class {
  constructor(t2, i2, e2) {
    __publicField(this, "start");
    __publicField(this, "end");
    __publicField(this, "source");
    this.start = t2, this.end = i2, this.source = e2;
  }
};
var e;
!function(t2) {
  t2.stylesheet = "stylesheet", t2.rule = "rule", t2.declaration = "declaration", t2.comment = "comment", t2.atRule = "at-rule", t2.container = "container", t2.charset = "charset", t2.counterStyle = "counter-style", t2.document = "document", t2.customMedia = "custom-media", t2.fontFace = "font-face", t2.fontFeatureValues = "font-feature-values", t2.host = "host", t2.import = "import", t2.keyframes = "keyframes", t2.keyframe = "keyframe", t2.layer = "layer", t2.media = "media", t2.namespace = "namespace", t2.page = "page", t2.pageMarginBox = "page-margin-box", t2.positionTry = "position-try", t2.property = "property", t2.scope = "scope", t2.startingStyle = "starting-style", t2.supports = "supports", t2.viewTransition = "view-transition";
}(e || (e = {}));
var s = (t2, i2, e2) => {
  let s2 = e2, n2 = 1e4;
  do {
    const e3 = i2.map((i3) => t2.indexOf(i3, s2));
    e3.push(t2.indexOf("\\", s2));
    const r2 = e3.filter((t3) => -1 !== t3);
    if (0 === r2.length)
      return -1;
    const o2 = Math.min(...r2);
    if ("\\" !== t2[o2])
      return o2;
    s2 = o2 + 2, n2--;
  } while (n2 > 0);
  throw new Error("Too many escaping");
};
var n = (t2, i2, e2) => {
  let r2 = e2, o2 = 1e4;
  do {
    const e3 = i2.map((i3) => t2.indexOf(i3, r2));
    e3.push(t2.indexOf("(", r2)), e3.push(t2.indexOf('"', r2)), e3.push(t2.indexOf("'", r2)), e3.push(t2.indexOf("\\", r2));
    const c2 = e3.filter((t3) => -1 !== t3);
    if (0 === c2.length)
      return -1;
    const h2 = Math.min(...c2);
    switch (t2[h2]) {
      case "\\":
        r2 = h2 + 2;
        break;
      case "(":
        {
          const i3 = n(t2, [")"], h2 + 1);
          if (-1 === i3)
            return -1;
          r2 = i3 + 1;
        }
        break;
      case '"':
        {
          const i3 = s(t2, ['"'], h2 + 1);
          if (-1 === i3)
            return -1;
          r2 = i3 + 1;
        }
        break;
      case "'":
        {
          const i3 = s(t2, ["'"], h2 + 1);
          if (-1 === i3)
            return -1;
          r2 = i3 + 1;
        }
        break;
      default:
        return h2;
    }
    o2--;
  } while (o2 > 0);
  throw new Error("Too many escaping");
};
var r = /\/\*[^]*?(?:\*\/|$)/g;
function o(t2) {
  return t2 ? t2.trim() : "";
}
function c(t2, i2) {
  const e2 = t2 && "string" == typeof t2.type, s2 = e2 ? t2 : i2;
  for (const i3 in t2) {
    const e3 = t2[i3];
    Array.isArray(e3) ? e3.forEach((t3) => {
      c(t3, s2);
    }) : e3 && "object" == typeof e3 && c(e3, s2);
  }
  return e2 && Object.defineProperty(t2, "parent", { configurable: true, writable: true, enumerable: false, value: i2 || null }), t2;
}
var h = class {
  constructor(t2) {
    __publicField(this, "level", 0);
    __publicField(this, "indentation", "  ");
    __publicField(this, "compress", false);
    "string" == typeof (t2 == null ? void 0 : t2.indent) && (this.indentation = t2 == null ? void 0 : t2.indent), (t2 == null ? void 0 : t2.compress) && (this.compress = true);
  }
  emit(t2, i2) {
    return t2;
  }
  indent(t2) {
    return this.level = this.level || 1, t2 ? (this.level += t2, "") : Array(this.level).join(this.indentation);
  }
  visit(t2) {
    switch (t2.type) {
      case e.stylesheet:
        return this.stylesheet(t2);
      case e.rule:
        return this.rule(t2);
      case e.declaration:
        return this.declaration(t2);
      case e.comment:
        return this.comment(t2);
      case e.container:
        return this.container(t2);
      case e.charset:
        return this.charset(t2);
      case e.counterStyle:
        return this.counterStyle(t2);
      case e.document:
        return this.document(t2);
      case e.customMedia:
        return this.customMedia(t2);
      case e.fontFace:
        return this.fontFace(t2);
      case e.fontFeatureValues:
        return this.fontFeatureValues(t2);
      case e.host:
        return this.host(t2);
      case e.import:
        return this.import(t2);
      case e.keyframes:
        return this.keyframes(t2);
      case e.keyframe:
        return this.keyframe(t2);
      case e.layer:
        return this.layer(t2);
      case e.media:
        return this.media(t2);
      case e.namespace:
        return this.namespace(t2);
      case e.page:
        return this.page(t2);
      case e.pageMarginBox:
        return this.pageMarginBox(t2);
      case e.positionTry:
        return this.positionTry(t2);
      case e.property:
        return this.property(t2);
      case e.scope:
        return this.scope(t2);
      case e.startingStyle:
        return this.startingStyle(t2);
      case e.supports:
        return this.supports(t2);
      case e.viewTransition:
        return this.viewTransition(t2);
      case e.atRule:
        return this.genericAtRule(t2);
    }
  }
  mapVisit(t2, i2) {
    let e2 = "";
    i2 = i2 || "";
    for (let s2 = 0, n2 = t2.length; s2 < n2; s2++)
      e2 += this.visit(t2[s2]), i2 && s2 < n2 - 1 && (e2 += this.emit(i2));
    return e2;
  }
  compile(t2) {
    return this.compress ? t2.stylesheet.rules.map(this.visit, this).join("") : this.stylesheet(t2);
  }
  stylesheet(t2) {
    return this.mapVisit(t2.stylesheet.rules, "\n\n");
  }
  comment(t2) {
    return this.compress ? this.emit("", t2.position) : this.emit(`${this.indent()}/*${t2.comment}*/`, t2.position);
  }
  container(t2) {
    return this.compress ? this.emit(`@container ${t2.container}`, t2.position) + this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : this.emit(`${this.indent()}@container ${t2.container}`, t2.position) + this.emit(` {
${this.indent(1)}`) + this.mapVisit(t2.rules, "\n\n") + this.emit(`
${this.indent(-1)}${this.indent()}}`);
  }
  layer(t2) {
    return this.compress ? this.emit(`@layer ${t2.layer}`, t2.position) + (t2.rules ? this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : ";") : this.emit(`${this.indent()}@layer ${t2.layer}`, t2.position) + (t2.rules ? this.emit(` {
${this.indent(1)}`) + this.mapVisit(t2.rules, "\n\n") + this.emit(`
${this.indent(-1)}${this.indent()}}`) : ";");
  }
  import(t2) {
    return this.emit(`@import ${t2.import};`, t2.position);
  }
  media(t2) {
    return this.compress ? this.emit(`@media ${t2.media}`, t2.position) + this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : this.emit(`${this.indent()}@media ${t2.media}`, t2.position) + this.emit(` {
${this.indent(1)}`) + this.mapVisit(t2.rules, "\n\n") + this.emit(`
${this.indent(-1)}${this.indent()}}`);
  }
  document(t2) {
    const i2 = `@${t2.vendor || ""}document ${t2.document}`;
    return this.compress ? this.emit(i2, t2.position) + this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : this.emit(i2, t2.position) + this.emit(`  {
${this.indent(1)}`) + this.mapVisit(t2.rules, "\n\n") + this.emit(`${this.indent(-1)}
}`);
  }
  charset(t2) {
    return this.emit(`@charset ${t2.charset};`, t2.position);
  }
  namespace(t2) {
    return this.emit(`@namespace ${t2.namespace};`, t2.position);
  }
  startingStyle(t2) {
    return this.compress ? this.emit("@starting-style", t2.position) + this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : this.emit(`${this.indent()}@starting-style`, t2.position) + this.emit(` {
${this.indent(1)}`) + this.mapVisit(t2.rules, "\n\n") + this.emit(`
${this.indent(-1)}${this.indent()}}`);
  }
  supports(t2) {
    return this.compress ? this.emit(`@supports ${t2.supports}`, t2.position) + this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : this.emit(`${this.indent()}@supports ${t2.supports}`, t2.position) + this.emit(` {
${this.indent(1)}`) + this.mapVisit(t2.rules, "\n\n") + this.emit(`
${this.indent(-1)}${this.indent()}}`);
  }
  keyframes(t2) {
    return this.compress ? this.emit(`@${t2.vendor || ""}keyframes ${t2.name}`, t2.position) + this.emit("{") + this.mapVisit(t2.keyframes) + this.emit("}") : this.emit(`@${t2.vendor || ""}keyframes ${t2.name}`, t2.position) + this.emit(` {
${this.indent(1)}`) + this.mapVisit(t2.keyframes, "\n") + this.emit(`${this.indent(-1)}}`);
  }
  keyframe(t2) {
    const i2 = t2.declarations;
    return this.compress ? this.emit(t2.values.join(","), t2.position) + this.emit("{") + this.mapVisit(i2) + this.emit("}") : this.emit(this.indent()) + this.emit(t2.values.join(", "), t2.position) + this.emit(` {
${this.indent(1)}`) + this.mapVisit(i2, "\n") + this.emit(`${this.indent(-1)}
${this.indent()}}
`);
  }
  page(t2) {
    if (this.compress) {
      const i3 = t2.selectors.length ? t2.selectors.join(", ") : "";
      return this.emit(`@page ${i3}`, t2.position) + this.emit("{") + this.mapVisit(t2.declarations) + this.emit("}");
    }
    const i2 = t2.selectors.length ? `${t2.selectors.join(", ")} ` : "";
    return this.emit(`@page ${i2}`, t2.position) + this.emit("{\n") + this.emit(this.indent(1)) + this.mapVisit(t2.declarations, "\n") + this.emit(this.indent(-1)) + this.emit("\n}");
  }
  pageMarginBox(t2) {
    return this.compress ? this.emit(`@${t2.name}`, t2.position) + this.emit("{") + this.mapVisit(t2.declarations) + this.emit("}") : this.emit(`${this.indent()}@${t2.name} `, t2.position) + this.emit("{\n") + this.emit(this.indent(1)) + this.mapVisit(t2.declarations, "\n") + this.emit(this.indent(-1)) + this.emit(`
${this.indent()}}`);
  }
  fontFace(t2) {
    return this.compress ? this.emit("@font-face", t2.position) + this.emit("{") + this.mapVisit(t2.declarations) + this.emit("}") : this.emit("@font-face ", t2.position) + this.emit("{\n") + this.emit(this.indent(1)) + this.mapVisit(t2.declarations, "\n") + this.emit(this.indent(-1)) + this.emit("\n}");
  }
  host(t2) {
    return this.compress ? this.emit("@host", t2.position) + this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : this.emit("@host", t2.position) + this.emit(` {
${this.indent(1)}`) + this.mapVisit(t2.rules, "\n\n") + this.emit(`${this.indent(-1)}
}`);
  }
  customMedia(t2) {
    return this.emit(`@custom-media ${t2.name} ${t2.media};`, t2.position);
  }
  property(t2) {
    return this.compress ? this.emit(`@property ${t2.name}`, t2.position) + this.emit("{") + this.mapVisit(t2.declarations) + this.emit("}") : this.emit(`@property ${t2.name} `, t2.position) + this.emit("{\n") + this.emit(this.indent(1)) + this.mapVisit(t2.declarations, "\n") + this.emit(this.indent(-1)) + this.emit("\n}");
  }
  counterStyle(t2) {
    return this.compress ? this.emit(`@counter-style ${t2.name}`, t2.position) + this.emit("{") + this.mapVisit(t2.declarations) + this.emit("}") : this.emit(`@counter-style ${t2.name} `, t2.position) + this.emit("{\n") + this.emit(this.indent(1)) + this.mapVisit(t2.declarations, "\n") + this.emit(this.indent(-1)) + this.emit("\n}");
  }
  fontFeatureValues(t2) {
    return this.compress ? this.emit(`@font-feature-values ${t2.fontFamily}`, t2.position) + this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : this.emit(`${this.indent()}@font-feature-values ${t2.fontFamily}`, t2.position) + this.emit(` {
${this.indent(1)}`) + this.mapVisit(t2.rules, "\n\n") + this.emit(`
${this.indent(-1)}${this.indent()}}`);
  }
  scope(t2) {
    const i2 = t2.scope ? ` ${t2.scope}` : "";
    return this.compress ? this.emit(`@scope${i2}`, t2.position) + this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : this.emit(`${this.indent()}@scope${i2}`, t2.position) + this.emit(` {
${this.indent(1)}`) + this.mapVisit(t2.rules, "\n\n") + this.emit(`
${this.indent(-1)}${this.indent()}}`);
  }
  viewTransition(t2) {
    return this.compress ? this.emit("@view-transition", t2.position) + this.emit("{") + this.mapVisit(t2.declarations) + this.emit("}") : this.emit("@view-transition ", t2.position) + this.emit("{\n") + this.emit(this.indent(1)) + this.mapVisit(t2.declarations, "\n") + this.emit(this.indent(-1)) + this.emit("\n}");
  }
  positionTry(t2) {
    return this.compress ? this.emit(`@position-try ${t2.name}`, t2.position) + this.emit("{") + this.mapVisit(t2.declarations) + this.emit("}") : this.emit(`@position-try ${t2.name} `, t2.position) + this.emit("{\n") + this.emit(this.indent(1)) + this.mapVisit(t2.declarations, "\n") + this.emit(this.indent(-1)) + this.emit("\n}");
  }
  genericAtRule(t2) {
    const i2 = t2.prelude ? ` ${t2.prelude}` : "";
    if (this.compress)
      return this.emit(`@${t2.name}${i2}`, t2.position) + (t2.rules ? this.emit("{") + this.mapVisit(t2.rules) + this.emit("}") : ";");
    if (!t2.rules)
      return this.emit(`${this.indent()}@${t2.name}${i2};`, t2.position);
    const s2 = t2.rules.some((t3) => t3.type !== e.declaration && t3.type !== e.comment), n2 = s2 ? "\n\n" : "\n";
    return this.emit(`${this.indent()}@${t2.name}${i2}`, t2.position) + this.emit(s2 ? ` {
${this.indent(1)}` : " {\n") + this.emit(s2 ? "" : this.indent(1)) + this.mapVisit(t2.rules, n2) + this.emit(s2 ? `
${this.indent(-1)}${this.indent()}}` : `${this.indent(-1)}
${this.indent()}}`);
  }
  rule(t2) {
    const i2 = t2.declarations;
    if (!i2.length)
      return "";
    if (this.compress)
      return this.emit(t2.selectors.join(","), t2.position) + this.emit("{") + this.mapVisit(i2) + this.emit("}");
    const e2 = this.indent();
    return this.emit(t2.selectors.map((t3) => e2 + t3).join(",\n"), t2.position) + this.emit(" {\n") + this.emit(this.indent(1)) + this.mapVisit(i2, "\n") + this.emit(this.indent(-1)) + this.emit(`
${this.indent()}}`);
  }
  declaration(t2) {
    return this.compress ? this.emit(`${t2.property}:${t2.value}`, t2.position) + this.emit(";") : "grid-template-areas" === t2.property ? this.emit(this.indent()) + this.emit(t2.property + ": " + t2.value.split("\n").join("\n".padEnd(22) + this.indent()), t2.position) + this.emit(";") : this.emit(this.indent()) + this.emit(`${t2.property}: ${t2.value}`, t2.position) + this.emit(";");
  }
};
var a = (s2, h2) => {
  h2 = h2 || {};
  let a2 = 1, m2 = 1;
  function u() {
    const t2 = { line: a2, column: m2 };
    return (e2) => (e2.position = new i(t2, { line: a2, column: m2 }, (h2 == null ? void 0 : h2.source) || ""), g(), e2);
  }
  const p = [];
  function l(i2) {
    const e2 = new t((h2 == null ? void 0 : h2.source) || "", i2, a2, m2, s2);
    if (!(h2 == null ? void 0 : h2.silent))
      throw e2;
    p.push(e2);
  }
  function f() {
    const t2 = /^{\s*/.exec(s2);
    return !!t2 && (y(t2), true);
  }
  function d() {
    const t2 = /^}/.exec(s2);
    return !!t2 && (y(t2), true);
  }
  function y(t2) {
    const i2 = t2[0];
    return function(t3) {
      const i3 = t3.match(/\n/g);
      i3 && (a2 += i3.length);
      const e2 = t3.lastIndexOf("\n");
      m2 = ~e2 ? t3.length - e2 : m2 + t3.length;
    }(i2), s2 = s2.slice(i2.length), t2;
  }
  function g() {
    const t2 = /^\s*/.exec(s2);
    t2 && y(t2);
  }
  function $(t2) {
    t2 = t2 || [];
    let i2 = x();
    for (; i2; )
      t2.push(i2), i2 = x();
    return t2;
  }
  function x() {
    const t2 = u();
    if ("/" !== s2.charAt(0) || "*" !== s2.charAt(1))
      return;
    const i2 = /^\/\*[^]*?\*\//.exec(s2);
    return i2 ? (y(i2), t2({ type: e.comment, comment: i2[0].slice(2, -2) })) : l("End of comment missing");
  }
  function V() {
    const t2 = n(s2, ["{"]);
    if (-1 === t2 || 0 === t2)
      return;
    const i2 = s2.substring(0, t2);
    y([i2]);
    return ((t3, i3) => {
      const e2 = [];
      let s3 = 0;
      for (; s3 < t3.length; ) {
        const r2 = n(t3, i3, s3);
        if (-1 === r2)
          return e2.push(t3.substring(s3)), e2;
        e2.push(t3.substring(s3, r2)), s3 = r2 + 1;
      }
      return e2;
    })(o(i2).replace(r, ""), [","]).map((t3) => o(t3));
  }
  function v() {
    const t2 = u(), i2 = /^(\*?[-#/*\\\w]+(\[[0-9a-z_-]+\])?)\s*/.exec(s2);
    if (!i2)
      return;
    y(i2);
    const c2 = o(i2[0]), h3 = /^:\s*/.exec(s2);
    if (!h3)
      return l("property missing ':'");
    y(h3);
    let a3 = "";
    const m3 = n(s2, [";", "}"]);
    if (-1 !== m3) {
      a3 = s2.substring(0, m3);
      y([a3]), a3 = o(a3).replace(r, "");
    }
    const p2 = t2({ type: e.declaration, property: c2.replace(r, ""), value: a3 }), f2 = /^[;\s]*/.exec(s2);
    return f2 && y(f2), p2;
  }
  function w() {
    const t2 = [];
    if (!f())
      return l("missing '{'");
    $(t2);
    let i2 = v();
    for (; i2; )
      t2.push(i2), $(t2), i2 = v();
    for (; (h2 == null ? void 0 : h2.silent) && s2.length && "}" !== s2.charAt(0); ) {
      const e2 = s2.indexOf(";"), n2 = s2.indexOf("}");
      if (-1 === e2 || !(-1 === n2 || e2 < n2))
        break;
      for (y([s2.substring(0, e2 + 1)]), g(), $(t2), i2 = v(); i2; )
        t2.push(i2), $(t2), i2 = v();
    }
    return d() ? t2 : l("missing '}'");
  }
  function b() {
    const t2 = n(s2, ["{"]);
    if (-1 === t2)
      return false;
    const i2 = n(s2, [";"]), e2 = n(s2, ["}"]);
    return !(-1 !== i2 && i2 < t2) && !(-1 !== e2 && e2 < t2);
  }
  function k() {
    const t2 = [];
    if (!f())
      return l("missing '{'");
    for ($(t2); s2.length && "}" !== s2.charAt(0); ) {
      if ("@" === s2.charAt(0)) {
        const i3 = E();
        if (i3) {
          t2.push(i3), $(t2);
          continue;
        }
      }
      if (b()) {
        const i3 = R();
        if (i3) {
          t2.push(i3), $(t2);
          continue;
        }
      }
      const i2 = v();
      if (!i2) {
        if (h2 == null ? void 0 : h2.silent) {
          const i3 = s2.indexOf(";"), e2 = s2.indexOf("}");
          if (-1 !== i3 && (-1 === e2 || i3 < e2)) {
            y([s2.substring(0, i3 + 1)]), g(), $(t2);
            continue;
          }
        }
        break;
      }
      t2.push(i2), $(t2);
    }
    return d() ? t2 : l("missing '}'");
  }
  function A() {
    const t2 = [];
    for (g(), $(t2); s2.length && "}" !== s2.charAt(0); ) {
      if ("@" === s2.charAt(0)) {
        const i3 = E();
        if (i3) {
          t2.push(i3), $(t2);
          continue;
        }
      }
      if (b()) {
        const i3 = R();
        if (i3) {
          t2.push(i3), $(t2);
          continue;
        }
      }
      const i2 = v();
      if (!i2) {
        if (h2 == null ? void 0 : h2.silent) {
          const i3 = s2.indexOf(";"), e2 = s2.indexOf("}");
          if (-1 !== i3 && (-1 === e2 || i3 < e2)) {
            y([s2.substring(0, i3 + 1)]), g(), $(t2);
            continue;
          }
        }
        break;
      }
      t2.push(i2), $(t2);
    }
    return t2;
  }
  function O() {
    const t2 = [], i2 = u();
    let n2 = /^((\d+\.\d+|\.\d+|\d+)%?|[a-z]+)\s*/.exec(s2);
    for (; n2; ) {
      const i3 = y(n2);
      t2.push(i3[1]);
      const e2 = /^,\s*/.exec(s2);
      e2 && y(e2), n2 = /^((\d+\.\d+|\.\d+|\d+)%?|[a-z]+)\s*/.exec(s2);
    }
    if (t2.length)
      return i2({ type: e.keyframe, values: t2, declarations: w() || [] });
  }
  const F = new RegExp(`^@(${["top-left-corner", "top-left", "top-center", "top-right", "top-right-corner", "bottom-left-corner", "bottom-left", "bottom-center", "bottom-right", "bottom-right-corner", "left-top", "left-middle", "left-bottom", "right-top", "right-middle", "right-bottom"].join("|")})(?![\\w-])\\s*`);
  const j = S("import"), M = S("charset"), T = S("namespace");
  function S(t2) {
    const i2 = new RegExp("^@" + t2 + `\\s*((?::?[^;'"]|"(?:\\\\"|[^"])*?"|'(?:\\\\'|[^'])*?')+)(?:;|$)`);
    return () => {
      const e2 = u(), n2 = i2.exec(s2);
      if (!n2)
        return;
      const r2 = y(n2), o2 = { type: t2 };
      return o2[t2] = r2[1].trim(), e2(o2);
    };
  }
  function E() {
    if ("@" === s2[0])
      return function() {
        const t2 = u(), i2 = /^@([-\w]+)?keyframes\s*/.exec(s2);
        if (!i2)
          return;
        const n2 = y(i2)[1], r2 = /^([-\w]+)\s*/.exec(s2);
        if (!r2)
          return l("@keyframes missing name");
        const o2 = y(r2)[1];
        if (!f())
          return l("@keyframes missing '{'");
        let c2 = $(), h3 = O();
        for (; h3; )
          c2.push(h3), c2 = c2.concat($()), h3 = O();
        return d() ? t2({ type: e.keyframes, name: o2, vendor: n2, keyframes: c2 }) : l("@keyframes missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@media *([^{]+)/.exec(s2);
        if (!i2)
          return;
        const n2 = o(y(i2)[1]);
        if (!f())
          return l("@media missing '{'");
        const r2 = A();
        return d() ? t2({ type: e.media, media: n2, rules: r2 }) : l("@media missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@custom-media\s+(--\S+)\s+([^{;\s][^{;]*);/.exec(s2);
        if (!i2)
          return;
        const n2 = y(i2);
        return t2({ type: e.customMedia, name: o(n2[1]), media: o(n2[2]) });
      }() || function() {
        const t2 = u(), i2 = /^@supports *([^{]+)/.exec(s2);
        if (!i2)
          return;
        const n2 = o(y(i2)[1]);
        if (!f())
          return l("@supports missing '{'");
        const r2 = A();
        return d() ? t2({ type: e.supports, supports: n2, rules: r2 }) : l("@supports missing '}'");
      }() || j() || M() || T() || function() {
        const t2 = u(), i2 = /^@([-\w]+)?document *([^{]+)/.exec(s2);
        if (!i2)
          return;
        const n2 = y(i2), r2 = o(n2[1]), c2 = o(n2[2]);
        if (!f())
          return l("@document missing '{'");
        const h3 = A();
        return d() ? t2({ type: e.document, document: c2, vendor: r2, rules: h3 }) : l("@document missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@page */.exec(s2);
        if (!i2)
          return;
        y(i2);
        const n2 = V() || [];
        if (!f())
          return l("@page missing '{'");
        const r2 = [];
        for ($(r2); s2.length && "}" !== s2.charAt(0); ) {
          if ("@" === s2.charAt(0)) {
            const t4 = E();
            if (t4) {
              r2.push(t4), $(r2);
              continue;
            }
          }
          const t3 = v();
          if (!t3)
            break;
          r2.push(t3), $(r2);
        }
        return d() ? t2({ type: e.page, selectors: n2, declarations: r2 }) : l("@page missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@host\s*/.exec(s2);
        if (!i2)
          return;
        if (y(i2), !f())
          return l("@host missing '{'");
        const n2 = A();
        return d() ? t2({ type: e.host, rules: n2 }) : l("@host missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@font-face\s*/.exec(s2);
        if (!i2)
          return;
        if (y(i2), !f())
          return l("@font-face missing '{'");
        let n2 = $(), r2 = v();
        for (; r2; )
          n2.push(r2), n2 = n2.concat($()), r2 = v();
        return d() ? t2({ type: e.fontFace, declarations: n2 }) : l("@font-face missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@font-feature-values\s+([^{]+)/.exec(s2);
        if (!i2)
          return;
        const n2 = o(y(i2)[1]);
        if (!f())
          return l("@font-feature-values missing '{'");
        const r2 = A();
        return d() ? t2({ type: e.fontFeatureValues, fontFamily: n2, rules: r2 }) : l("@font-feature-values missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@container *([^{]+)/.exec(s2);
        if (!i2)
          return;
        const n2 = o(y(i2)[1]);
        if (!f())
          return l("@container missing '{'");
        const r2 = A();
        return d() ? t2({ type: e.container, container: n2, rules: r2 }) : l("@container missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@starting-style\s*/.exec(s2);
        if (!i2)
          return;
        if (y(i2), !f())
          return l("@starting-style missing '{'");
        const n2 = A();
        return d() ? t2({ type: e.startingStyle, rules: n2 }) : l("@starting-style missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@layer *([^{;@]+)/.exec(s2);
        if (!i2)
          return;
        const n2 = o(y(i2)[1]);
        if (!f()) {
          const i3 = /^[;\s]*/.exec(s2);
          return i3 && y(i3), t2({ type: e.layer, layer: n2 });
        }
        const r2 = A();
        return d() ? t2({ type: e.layer, layer: n2, rules: r2 }) : l("@layer missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@property\s+(--[-\w]+)\s*/.exec(s2);
        if (!i2)
          return;
        const n2 = y(i2)[1];
        if (!f())
          return l("@property missing '{'");
        let r2 = $(), o2 = v();
        for (; o2; )
          r2.push(o2), r2 = r2.concat($()), o2 = v();
        return d() ? t2({ type: e.property, name: n2, declarations: r2 }) : l("@property missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@counter-style\s+([-\w]+)\s*/.exec(s2);
        if (!i2)
          return;
        const n2 = y(i2)[1];
        if (!f())
          return l("@counter-style missing '{'");
        let r2 = $(), o2 = v();
        for (; o2; )
          r2.push(o2), r2 = r2.concat($()), o2 = v();
        return d() ? t2({ type: e.counterStyle, name: n2, declarations: r2 }) : l("@counter-style missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@scope\s*([^{]*)/.exec(s2);
        if (!i2)
          return;
        const n2 = o(y(i2)[1]);
        if (!f())
          return l("@scope missing '{'");
        const r2 = A();
        return d() ? t2({ type: e.scope, scope: n2, rules: r2 }) : l("@scope missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@view-transition\s*/.exec(s2);
        if (!i2)
          return;
        if (y(i2), !f())
          return l("@view-transition missing '{'");
        let n2 = $(), r2 = v();
        for (; r2; )
          n2.push(r2), n2 = n2.concat($()), r2 = v();
        return d() ? t2({ type: e.viewTransition, declarations: n2 }) : l("@view-transition missing '}'");
      }() || function() {
        const t2 = u(), i2 = /^@position-try\s+(--[-\w]+)\s*/.exec(s2);
        if (!i2)
          return;
        const n2 = y(i2)[1];
        if (!f())
          return l("@position-try missing '{'");
        let r2 = $(), o2 = v();
        for (; o2; )
          r2.push(o2), r2 = r2.concat($()), o2 = v();
        return d() ? t2({ type: e.positionTry, name: n2, declarations: r2 }) : l("@position-try missing '}'");
      }() || function() {
        const t2 = u(), i2 = F.exec(s2);
        if (!i2)
          return;
        const n2 = y(i2)[1];
        if (!f())
          return l(`@${n2} missing '{'`);
        let r2 = $(), o2 = v();
        for (; o2; )
          r2.push(o2), r2 = r2.concat($()), o2 = v();
        return d() ? t2({ type: e.pageMarginBox, name: n2, declarations: r2 }) : l(`@${n2} missing '}'`);
      }() || function() {
        const t2 = u(), i2 = /^@([-\w]+)\s*/.exec(s2);
        if (!i2)
          return;
        const r2 = y(i2)[1];
        let c2 = "";
        const h3 = n(s2, ["{", ";"]);
        -1 !== h3 && h3 > 0 && (c2 = o(s2.substring(0, h3)), y([s2.substring(0, h3)]));
        if (f()) {
          const i3 = A();
          return d() ? t2({ type: e.atRule, name: r2, prelude: c2, rules: i3 }) : l(`@${r2} missing '}'`);
        }
        const a3 = /^[;\s]*/.exec(s2);
        return a3 && y(a3), t2({ type: e.atRule, name: r2, prelude: c2 });
      }();
  }
  function R() {
    const t2 = u(), i2 = V();
    return i2 ? ($(), t2({ type: e.rule, selectors: i2, declarations: k() || [] })) : l("selector missing");
  }
  return c(function() {
    const t2 = function() {
      let t3;
      const i2 = [];
      g(), $(i2);
      for (; s2.length; ) {
        if ("}" === s2.charAt(0)) {
          if (h2 == null ? void 0 : h2.silent) {
            l("extra '}'");
            y(["}"]), g(), $(i2);
            continue;
          }
          break;
        }
        if (t3 = E() || R(), !t3) {
          if (h2 == null ? void 0 : h2.silent) {
            y([s2.charAt(0)]), g(), $(i2);
            continue;
          }
          break;
        }
        i2.push(t3), $(i2);
      }
      return i2;
    }();
    return { type: e.stylesheet, stylesheet: { source: h2 == null ? void 0 : h2.source, rules: t2, parsingErrors: p } };
  }());
};
var m = (t2, i2) => new h(i2 || {}).compile(t2);

// src/io/inlineAdmonitionCss.ts
var snippetName = "inlineAdmonitionsPluginReadOnly";
var snippetFilename = snippetName + ".css";
var header = `/*
WARNING: THIS FILE IS AUTOGENERATED BY THE INLINE ADMONITION PLUGIN. DO NOT MODIFY!
*/
`;
async function setCssForClass(app, className, css) {
  const updatedCss = _setCssForClass(className, css, await cssFileContents(app));
  const customCss = app.customCss;
  customCss.setCssEnabledStatus(snippetName, true);
  await customCss.readSnippets();
  await customCss.requestLoadSnippets();
  return writeSnippetFile(app, snippetFilename, updatedCss);
}
async function wipeCss(app) {
  if (await snippetExists(app, snippetFilename)) {
    return writeSnippetFile(app, snippetFilename, header);
  } else {
    return createSnippetFile(app, snippetFilename, header);
  }
}
async function cssFileContents(app) {
  return readSnippetFile(app, snippetFilename);
}
function _setCssForClass(className, cssClassDeclarations, cssFileContent) {
  var _a, _b, _c;
  const fileObj = a(cssFileContent);
  const rules = (_b = (_a = fileObj.stylesheet) == null ? void 0 : _a.rules) != null ? _b : [];
  for (const rule of rules) {
    if (rule.type === e.rule && ((_c = rule.selectors) == null ? void 0 : _c.contains("." + className))) {
      rule.declarations = _makeCssRule(className, cssClassDeclarations).declarations;
      return m(fileObj);
    }
  }
  rules.push(_makeCssRule(className, cssClassDeclarations));
  return m(fileObj);
}
function _makeCssRuleString(className, cssDeclarations) {
  return ".iad." + className + " {\n" + cssDeclarations + "\n}";
}
function _makeCssRule(className, cssDeclarations) {
  var _a, _b;
  const cssString = _makeCssRuleString(className, cssDeclarations);
  const rule = ((_b = (_a = a(cssString).stylesheet) == null ? void 0 : _a.rules) != null ? _b : [])[0];
  if ((rule == null ? void 0 : rule.type) !== e.rule) {
    throw new Error("Failed to construct CSS rule for class " + className);
  }
  return rule;
}

// main.ts
var InlineAdmonitionPlugin = class extends import_obsidian10.Plugin {
  async onload() {
    this.inlineAdmonitionCompartment = new import_state2.Compartment();
    await this.loadSettings();
    const extension = this.inlineAdmonitionCompartment.of(
      inlineAdmonitionPlugin(Array.from(this.settings.inlineAdmonitions.values()))
    );
    this.registerEditorExtension(extension);
    this.registerMarkdownPostProcessor((element, context) => {
      new InlineAdmonitionsPostProcessor(this.settings).postProcess(element, context);
    });
    this.addSettingTab(new InlineAdmonitionSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    const settingData = await this.loadData();
    const [settings, dataMigrated] = InlineAdmonitionSettingsIO.unmarshalAndMigrate(settingData);
    this.settings = settings;
    if (dataMigrated) {
      await this.saveSettings();
    }
    await this.refreshCss();
  }
  async saveSettings() {
    const settingData = InlineAdmonitionSettingsIO.marshal(this.settings);
    await this.saveData(settingData);
    await this.refreshCss();
    this.rerenderMarkdownViews();
    this.updateEditorExtensions();
  }
  async refreshCss() {
    await wipeCss(this.app);
    for (const iad of this.settings.inlineAdmonitions.values()) {
      const classes = iad.cssClasses();
      await setCssForClass(this.app, classes[classes.length - 1], iad.simpleStyle());
    }
  }
  rerenderMarkdownViews() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian10.MarkdownView);
    view == null ? void 0 : view.previewMode.rerender(true);
  }
  updateEditorExtensions() {
    const newExtension = inlineAdmonitionPlugin(Array.from(this.settings.inlineAdmonitions.values()));
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.view instanceof import_obsidian10.MarkdownView && leaf.view.editor) {
        const cm = leaf.view.editor.cm;
        cm.dispatch({
          effects: this.inlineAdmonitionCompartment.reconfigure(newExtension)
        });
      }
    });
  }
};

/* nosourcemap */